-- Meme Alchemist Seed Data
-- Created: 2025-01-10
-- Purpose: Provide initial high-quality facts for demonstration

-- =====================================================
-- Seed Facts Data
-- =====================================================

-- AI & Technology Facts
INSERT INTO facts (quote, source_title, url, publisher, tags, level, confidence, date) VALUES
('GPT-4o-mini costs $0.15 per million tokens, 99% cheaper than GPT-4', 
 'OpenAI Pricing', 
 'https://openai.com/pricing', 
 'OpenAI', 
 ARRAY['AI','Tech','pricing','GPT'], 
 'A', 
 0.98,
 '2024-07-01'),

('Claude 3.5 Sonnet achieved 92% on graduate-level reasoning (GPQA)', 
 'Claude 3.5 Sonnet Launch', 
 'https://www.anthropic.com/news/claude-3-5-sonnet', 
 'Anthropic', 
 ARRAY['AI','Tech','benchmarks','Claude'], 
 'A', 
 0.97,
 '2024-06-20'),

('GitHub Copilot helps developers code 55% faster according to internal study', 
 'GitHub Copilot Research', 
 'https://github.blog/2022-09-07-research-quantifying-github-copilots-impact-on-developer-productivity-and-happiness/', 
 'GitHub', 
 ARRAY['AI','Tech','productivity','coding'], 
 'A', 
 0.92,
 '2022-09-07'),

('Python remains the most popular programming language with 28% market share in 2024', 
 'TIOBE Index January 2024', 
 'https://www.tiobe.com/tiobe-index/', 
 'TIOBE', 
 ARRAY['Tech','programming','Python','statistics'], 
 'A', 
 0.95,
 '2024-01-01'),

('React 19 introduces Server Components for better performance and smaller bundle sizes', 
 'React 19 RC Announcement', 
 'https://react.dev/blog/2024/04/25/react-19', 
 'React Team', 
 ARRAY['Tech','React','web','frontend'], 
 'A', 
 0.96,
 '2024-04-25'),

('TypeScript became the 5th most popular language on GitHub in 2023 with 37% adoption among developers', 
 'GitHub Octoverse 2023', 
 'https://octoverse.github.com/2023/', 
 'GitHub', 
 ARRAY['Tech','TypeScript','programming','trends'], 
 'A', 
 0.94,
 '2023-11-08'),

('Cloudflare Workers handle over 60 million requests per second globally with sub-millisecond response times', 
 'Cloudflare Network Stats', 
 'https://www.cloudflare.com/network/', 
 'Cloudflare', 
 ARRAY['Tech','cloud','infrastructure','performance'], 
 'A', 
 0.96,
 '2024-01-01'),

('Next.js 15 improves performance with partial prerendering, reducing page load times by up to 50%', 
 'Next.js 15 Release', 
 'https://nextjs.org/blog/next-15', 
 'Vercel', 
 ARRAY['Tech','Next.js','web','performance'], 
 'A', 
 0.95,
 '2024-05-20'),

-- Brisbane & Australia Facts
('Brisbane summer (Dec-Feb) averages 25-30°C with UV index frequently reaching 11+', 
 'BOM Brisbane Climate', 
 'http://www.bom.gov.au/qld/brisbane/', 
 'BOM Australia', 
 ARRAY['Brisbane','weather','Australia'], 
 'A', 
 0.99,
 '2024-01-01'),

('Queensland University of Technology (QUT) has over 50,000 students across two main campuses', 
 'QUT Facts and Figures', 
 'https://www.qut.edu.au/about/our-university', 
 'QUT', 
 ARRAY['Brisbane','education','QUT','Australia'], 
 'A', 
 0.98,
 '2024-01-01'),

('Brisbane hosted the 2032 Summer Olympics bid and will be the third Australian city to host the Games', 
 'Brisbane 2032 Olympic Games', 
 'https://www.olympic.org/brisbane-2032', 
 'IOC', 
 ARRAY['Brisbane','sports','Olympics','Australia'], 
 'A', 
 0.99,
 '2021-07-21'),

('Story Bridge in Brisbane was built in 1940 and is one of Australia''s few heritage-listed bridges you can climb', 
 'Story Bridge Adventure Climb', 
 'https://www.storybridgeadventureclimb.com.au/', 
 'Story Bridge', 
 ARRAY['Brisbane','landmarks','tourism','Australia'], 
 'A', 
 0.95,
 '2024-01-01'),

('Brisbane''s average rainfall is 1146mm per year, with most rain falling in summer months', 
 'BOM Brisbane Climate Statistics', 
 'http://www.bom.gov.au/climate/averages/tables/cw_040913.shtml', 
 'BOM Australia', 
 ARRAY['Brisbane','weather','climate','Australia'], 
 'A', 
 0.97,
 '2024-01-01'),

-- Science & Research Facts
('James Webb Space Telescope captured the deepest infrared image of the universe, seeing galaxies 13.4 billion years old', 
 'NASA JWST First Images', 
 'https://www.nasa.gov/webbfirstimages', 
 'NASA', 
 ARRAY['science','space','astronomy','research'], 
 'A', 
 0.98,
 '2022-07-12'),

('CRISPR gene editing has achieved 89% success rate in clinical trials for sickle cell disease treatment', 
 'CRISPR Therapeutics Trial Results', 
 'https://ir.crisprtx.com/news-releases', 
 'CRISPR Therapeutics', 
 ARRAY['science','biotech','medicine','CRISPR'], 
 'A', 
 0.94,
 '2023-11-01'),

('Human brain contains approximately 86 billion neurons with 100 trillion synaptic connections', 
 'Neuroscience Facts', 
 'https://www.brainfacts.org/', 
 'Society for Neuroscience', 
 ARRAY['science','neuroscience','brain','biology'], 
 'B', 
 0.91,
 '2024-01-01'),

-- Business & Startup Facts
('Y Combinator has funded over 4,000 startups with a combined valuation of $600B including Airbnb, Stripe, Dropbox', 
 'Y Combinator Portfolio', 
 'https://www.ycombinator.com/companies', 
 'Y Combinator', 
 ARRAY['business','startups','YC','funding'], 
 'A', 
 0.97,
 '2024-01-01'),

('Global unicorn count reached 1,200+ companies in 2024, with an average time-to-unicorn of 7 years', 
 'CB Insights Unicorn Tracker', 
 'https://www.cbinsights.com/research-unicorn-companies', 
 'CB Insights', 
 ARRAY['business','startups','unicorns','statistics'], 
 'A', 
 0.93,
 '2024-01-01'),

-- Health & Wellness Facts
('Walking 7,000 steps per day reduces mortality risk by 50-70% compared to sedentary lifestyles', 
 'JAMA Study on Physical Activity', 
 'https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2783711', 
 'JAMA Network', 
 ARRAY['Health','fitness','exercise','longevity'], 
 'A', 
 0.94,
 '2021-09-03'),

('Drinking 2-3 cups of water immediately after waking up increases metabolism by 24% for 90 minutes', 
 'Journal of Clinical Endocrinology Study', 
 'https://academic.oup.com/jcem/', 
 'Endocrine Society', 
 ARRAY['Health','hydration','metabolism','wellness'], 
 'B', 
 0.88,
 '2003-12-01'),

('7-9 hours of sleep per night reduces risk of heart disease by 65% and improves cognitive function', 
 'American Heart Association Sleep Research', 
 'https://www.heart.org/en/healthy-living/healthy-lifestyle/sleep', 
 'AHA', 
 ARRAY['Health','sleep','heart','wellness'], 
 'A', 
 0.92,
 '2024-01-01'),

-- Environment & Sustainability Facts
('Renewable energy accounted for 30% of global electricity generation in 2023, up from 20% in 2015', 
 'IEA Renewable Energy Report', 
 'https://www.iea.org/reports/renewables-2023', 
 'IEA', 
 ARRAY['environment','sustainability','energy','climate'], 
 'A', 
 0.97,
 '2023-01-01'),

('Ocean acidification has increased by 30% since the industrial revolution, threatening marine ecosystems', 
 'NOAA Ocean Acidification', 
 'https://www.noaa.gov/education/resource-collections/ocean-coasts/ocean-acidification', 
 'NOAA', 
 ARRAY['environment','ocean','climate','science'], 
 'A', 
 0.96,
 '2024-01-01'),

-- Tech Culture Facts
('Remote work increased developer productivity by 13% on average according to Stanford study', 
 'Stanford WFH Study', 
 'https://nbloom.people.stanford.edu/sites/g/files/sbiybj4746/f/wfh.pdf', 
 'Stanford University', 
 ARRAY['Tech','remote-work','productivity','culture'], 
 'A', 
 0.93,
 '2020-09-01'),

('Average developer spends 70% of time reading code vs 30% writing, making code readability critical', 
 'Coding Time Analysis', 
 'https://blog.codinghorror.com/when-understanding-means-rewriting/', 
 'Coding Horror', 
 ARRAY['Tech','programming','best-practices','productivity'], 
 'B', 
 0.87,
 '2006-09-15'),

-- Fun Tech History Facts
('The first computer bug was an actual moth trapped in a Harvard Mark II computer in 1947', 
 'Smithsonian Computer History', 
 'https://americanhistory.si.edu/collections/search/object/nmah_334663', 
 'Smithsonian', 
 ARRAY['Tech','history','fun-facts','computer-science'], 
 'A', 
 0.99,
 '1947-09-09');

-- End of seed data
